export const SET_REGISTERED = "SET_REGISTERED";
export const SET_UNREGISTERED = "SET_UNREGISTERED";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";

export const UPDATE_USERDATA = "UPDATE_USERDATA";
export const UPDATE_USERTOKEN = "UPDATE_USERTOKEN";

//USER
export const SET_USER = "SET_USER";

//USER_DATA
export const DELETE_USER = "DELETE_USER";

//POSTS
export const SET_POSTS = "SET_POSTS";