//USER_DATA
export const SET_USER = "SET_USER";
export const UPDATE_USERDATA = "UPDATE_USERDATA";
export const UPDATE_USERTOKEN = "UPDATE_USERTOKEN";

//USER
export const DELETE_USER = "DELETE_USER";
export const SET_REGISTERED = "SET_REGISTERED";
export const SET_UNREGISTERED = "SET_UNREGISTERED";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";

//POSTS
export const SET_POSTS = "SET_POSTS";
export const ADD_POST = "ADD_POST";
export const REMOVE_POST = "REMOVE_POST";
export const ADD_COMMENT = "ADD_COMMENT";